server:
  port: 8080
  origin: ${ORIGIN:*}
  servlet:
    context-path: /commands
spring:
  application:
    name: gamecommands
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}  
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/test}

microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.commandhandles}
  storeName: ${STORE_NAME:game}
  routingKey: ${ROUTING_KEY:cardgame.#}




