server:
  port: 8085
  origin: ${ORIGIN:*}
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: master
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://cardgameuser:cHCoyN5zPgLTkLGs@cardgamedb.isainvn.mongodb.net/master?retryWrites=true&w=majority}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin: # All zipkin features disabled for integration tests
    enabled: false