server:
  port: 8080
  origin: ${ORIGIN:*}
spring:
  application:
    name: game-commands
  main:
    banner-mode: off
  output:
    ansi:
    enabled: ALWAYS
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqps://kjtvgvhd:bHmdR5lNP-mrTr-lhe20E1Zvk1NjoBbC@chimpanzee.rmq.cloudamqp.com/kjtvgvhd}
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb+srv://cardgameuser:cHCoyN5zPgLTkLGs@cardgamedb.isainvn.mongodb.net/game-events?retryWrites=true&w=majority}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin: # All zipkin features disabled for integration tests
    enabled: false
microservice:
  exchange: ${EXCHANGE:core-game}
  queue: ${QUEUE:game.commandhandles}
  storeName: ${STORE_NAME:game}
  routingKey: ${ROUTING_KEY:cardgame.#}




