mongodb:
  mongodbUsername: userCore
  mongodbPassword: MongoDBPassword
  mongodbDatabase: queries
  architecture: replicaset
  replicaCount: 1
  pdb.create: true

rabbitmq:
  pdb.create: true
  replicaCount: 1
  auth:
    erlangCookie: cardgameCore
    username: userCore
    password: RabbitMQPassword
  memoryHighWatermark.enabled: true

mongo_uri: "mongodb://userCore:MongoDBPassword@core-cardgame-mongodb:27017/queries"
rabbitmq_uri: "amqp://userCore:RabbitMQPassword@core-cardgame-rabbitmq:5672"
master_uri: "http://cardgame-master:8085"

command:
  repository: 316078593388.dkr.ecr.us-east-1.amazonaws.com/raul-command:latest
  pullPolicy: Always

queries:
  repository: 316078593388.dkr.ecr.us-east-1.amazonaws.com/raul-queries:latest
  pullPolicy: Always

proxy:
  repository: 316078593388.dkr.ecr.us-east-1.amazonaws.com/raul-proxy:latest
  pullPolicy: Always


gateway:
  repository: 316078593388.dkr.ecr.us-east-1.amazonaws.com/raul-gateway:latest
  pullPolicy: Always

master:
  repository: 316078593388.dkr.ecr.us-east-1.amazonaws.com/raul-master:latest
  pullPolicy: Always

ingress:
  host: localhost